export const VOICE_AGENT_KEYWORDS = [
  'AI voice assistant for restaurants',
  'AI voice agent restaurant booking',
  'automated table booking system',
  'AI reservation system',
  'voice AI booking agent',
  'conversational AI for restaurants',
  'AI voice assistant bus ticket booking',
  'automated booking voice agent',
  'voice-activated reservation system',
  'AI call center automation',
  'AI call center automationinfyom',
  'AI that books restaurant tables automatically',
  'voice assistant that handles phone reservations',
  'AI agent for automated table booking 24/7',
  'conversational AI for customer service calls',
  'human-like voice assistant for bookings',
  'AI voice agent that sounds like a human',
  'automated restaurant reservation voice system',
  'AI assistant for bus ticket booking online',
  'voice AI that handles customer calls naturally',
  'smart voice agent for multi-service booking',
  'smart voice agent for multi-service bookingpremierecreative+1',
  '24/7 AI booking assistant',
  'natural language voice AI agent',
  'multi-lingual voice assistant booking',
  'AI voice agent with real-time availability',
  'automated voice reservation system',
  'voice AI with human-like conversation',
  'AI agent for phone call automation',
  'voice assistant with calendar integration',
  'conversational booking agent AI',
  'intelligent voice response system',
  'intelligent voice response systemdigitaldelane+1',
  'voice AI for restaurant call handling',
  'automated bus booking voice assistant',
  'AI voice agent for hospitality industry',
  'voice assistant for travel booking',
  'AI receptionist for restaurants',
  'automated customer service voice agent',
  'voice AI for transportation booking',
  'smart assistant for table reservations',
  'AI voice bot for ticket booking',
  'conversational agent for service booking',
  'conversational agent for service bookingjnextservices+1',
  'restaurant voice automation solution',
  'hospitality AI voice assistant',
  'travel booking voice AI',
  'food service automation AI',
  'voice agent for dining reservations',
  'AI assistant for quick service restaurants',
  'voice automation for restaurant chains',
  'bus ticket booking AI solution',
  'customer service voice AI platform',
  'reservation management voice agent',
  'reservation management voice agentjploft+1',
  'Twilio voice AI integration',
  'Vapi voice assistant solution',
  'AI voice agent with POS integration',
  'voice assistant API for booking systems',
  'cloud-based voice AI agent',
  'voice agent with CRM integration',
  'AI assistant with Google Sheets sync',
  'voice AI with real-time database sync',
  'conversational AI with API connectivity',
  'voice agent scheduling integration',
  'voice agent scheduling integrationinfyom',
  'how does AI voice assistant handle restaurant bookings',
  'what is automated voice booking system',
  'best AI voice agent for restaurant reservations',
  'how to automate table booking with voice AI',
  'what are AI voice assistants for customer service',
  'how does conversational AI booking work',
  'which voice AI handles bus ticket booking',
  'how to implement voice assistant for reservations',
  'what is voice automation for restaurants',
  'best voice AI for booking management',
  'best voice AI for booking managementpremierecreative+1',
  'reduce missed restaurant bookings with AI',
  '24/7 reservation availability voice assistant',
  'increase booking efficiency with voice AI',
  'AI voice agent saves staff time',
  'automated booking reduces manual errors',
  'voice assistant improves customer experience',
  'AI agent handles peak hour calls',
  'voice automation for after-hours booking',
  'scalable voice AI for multiple locations',
  'cost-effective voice booking solution',
];

export const VOICE_AGENT_KEYWORDS_STRING = VOICE_AGENT_KEYWORDS.join(', ');

